# Generated by Django 3.1.1 on 2020-10-04 12:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('outline', models.TextField(null=True)),
                ('aouthor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='投票日時')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.comic'),
        ),
    ]
