# Generated by Django 3.1.1 on 2020-09-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('aouthor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='comic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.comic'),
        ),
    ]
