# Generated by Django 3.1.1 on 2020-10-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='aouthor',
            new_name='author',
        ),
    ]
