# Generated by Django 3.1.1 on 2020-09-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voting_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='comic_id',
            new_name='comic',
        ),
    ]
