# Generated by Django 3.1.1 on 2020-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200929_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='outline',
            field=models.TextField(null=True),
        ),
    ]
